services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto_files/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_files/config/mosquitto.conf:/mosquitto/config/pwfile
      - ./mosquitto_files/data:/mosquitto/data
      - ./mosquitto_files/log:/mosquitto/log
    security_opt:
      - no-new-privileges:true